apiVersion: v1
kind: Service
metadata:
  name: kubedeploy
  labels:
    version: 0.0.1
spec:
  ports:
    - port: 80
      targetPort: 8081
      name: http
      protocol: TCP
  selector:
    app: kubedeploy
